// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OperationsPortal.Api.Data;

#nullable disable

namespace OperationsPortal.Api.Migrations
{
    [DbContext(typeof(OperationsPortalContext))]
    [Migration("20260913031208_EntityConfigurations")]
    partial class EntityConfigurations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OperationsPortal.Api.Models.BomHeader", b =>
                {
                    b.Property<int>("BomHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bom_header_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BomHeaderId"));

                    b.Property<string>("BomHeaderName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bom_header_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.HasKey("BomHeaderId")
                        .HasName("pk_bom_headers");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_bom_headers_item_id");

                    b.ToTable("bom_headers", (string)null);
                });

            modelBuilder.Entity("OperationsPortal.Api.Models.BomLine", b =>
                {
                    b.Property<int>("BomLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bom_line_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BomLineId"));

                    b.Property<int>("BomHeaderId")
                        .HasColumnType("integer")
                        .HasColumnName("bom_header_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<decimal>("QuantityPerAssembly")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity_per_assembly");

                    b.HasKey("BomLineId")
                        .HasName("pk_bom_lines");

                    b.HasIndex("BomHeaderId")
                        .HasDatabaseName("ix_bom_lines_bom_header_id");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_bom_lines_item_id");

                    b.ToTable("bom_lines", (string)null);
                });

            modelBuilder.Entity("OperationsPortal.Api.Models.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("inventory_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InventoryId"));

                    b.Property<int>("InventoryLocationId")
                        .HasColumnType("integer")
                        .HasColumnName("inventory_location_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.HasKey("InventoryId")
                        .HasName("pk_inventories");

                    b.HasIndex("InventoryLocationId")
                        .HasDatabaseName("ix_inventories_inventory_location_id");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_inventories_item_id");

                    b.ToTable("inventories", (string)null);
                });

            modelBuilder.Entity("OperationsPortal.Api.Models.InventoryLocation", b =>
                {
                    b.Property<int>("InventoryLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("inventory_location_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InventoryLocationId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("InventoryLocationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("inventory_location_name");

                    b.Property<int>("SubsiteId")
                        .HasColumnType("integer")
                        .HasColumnName("subsite_id");

                    b.HasKey("InventoryLocationId")
                        .HasName("pk_inventory_locations");

                    b.HasIndex("SubsiteId")
                        .HasDatabaseName("ix_inventory_locations_subsite_id");

                    b.ToTable("inventory_locations", (string)null);
                });

            modelBuilder.Entity("OperationsPortal.Api.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_name");

                    b.Property<string>("ItemNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_number");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_type");

                    b.Property<int>("UnitOfMeasureId")
                        .HasColumnType("integer")
                        .HasColumnName("unit_of_measure_id");

                    b.HasKey("ItemId")
                        .HasName("pk_items");

                    b.HasIndex("UnitOfMeasureId")
                        .HasDatabaseName("ix_items_unit_of_measure_id");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("OperationsPortal.Api.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId")
                        .HasName("pk_role");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("OperationsPortal.Api.Models.Site", b =>
                {
                    b.Property<int>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("site_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SiteId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("site_name");

                    b.HasKey("SiteId")
                        .HasName("pk_sites");

                    b.ToTable("sites", (string)null);
                });

            modelBuilder.Entity("OperationsPortal.Api.Models.Subsite", b =>
                {
                    b.Property<int>("SubsiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("subsite_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubsiteId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("site_id");

                    b.Property<string>("SubsiteName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subsite_name");

                    b.HasKey("SubsiteId")
                        .HasName("pk_subsites");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_subsites_site_id");

                    b.ToTable("subsites", (string)null);
                });

            modelBuilder.Entity("OperationsPortal.Api.Models.UnitOfMeasure", b =>
                {
                    b.Property<int>("UnitOfMeasureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("unit_of_measure_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UnitOfMeasureId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("UnitOfMeasureName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_of_measure_name");

                    b.HasKey("UnitOfMeasureId")
                        .HasName("pk_unit_of_measures");

                    b.ToTable("unit_of_measures", (string)null);
                });

            modelBuilder.Entity("OperationsPortal.Api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("OperationsPortal.Api.Models.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserRoleId"));

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("UserRoleId")
                        .HasName("pk_user_role");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_role_role_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_role_user_id");

                    b.ToTable("user_role", (string)null);
                });

            modelBuilder.Entity("OperationsPortal.Api.Models.BomHeader", b =>
                {
                    b.HasOne("OperationsPortal.Api.Models.Item", "Item")
                        .WithMany("BomHeaders")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bom_headers_items_item_id");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("OperationsPortal.Api.Models.BomLine", b =>
                {
                    b.HasOne("OperationsPortal.Api.Models.BomHeader", "BomHeader")
                        .WithMany("BomLines")
                        .HasForeignKey("BomHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bom_lines_bom_headers_bom_header_id");

                    b.HasOne("OperationsPortal.Api.Models.Item", "Item")
                        .WithMany("BomLines")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bom_lines_items_item_id");

                    b.Navigation("BomHeader");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("OperationsPortal.Api.Models.Inventory", b =>
                {
                    b.HasOne("OperationsPortal.Api.Models.InventoryLocation", "InventoryLocation")
                        .WithMany("Inventories")
                        .HasForeignKey("InventoryLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventories_inventory_locations_inventory_location_id");

                    b.HasOne("OperationsPortal.Api.Models.Item", "Item")
                        .WithMany("Inventories")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventories_items_item_id");

                    b.Navigation("InventoryLocation");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("OperationsPortal.Api.Models.InventoryLocation", b =>
                {
                    b.HasOne("OperationsPortal.Api.Models.Subsite", "Subsite")
                        .WithMany("InventoryLocations")
                        .HasForeignKey("SubsiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_locations_subsites_subsite_id");

                    b.Navigation("Subsite");
                });

            modelBuilder.Entity("OperationsPortal.Api.Models.Item", b =>
                {
                    b.HasOne("OperationsPortal.Api.Models.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany("Items")
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_items_unit_of_measures_unit_of_measure_id");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("OperationsPortal.Api.Models.Subsite", b =>
                {
                    b.HasOne("OperationsPortal.Api.Models.Site", "Site")
                        .WithMany("Subsites")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subsites_sites_site_id");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("OperationsPortal.Api.Models.UserRole", b =>
                {
                    b.HasOne("OperationsPortal.Api.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_role_role_id");

                    b.HasOne("OperationsPortal.Api.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OperationsPortal.Api.Models.BomHeader", b =>
                {
                    b.Navigation("BomLines");
                });

            modelBuilder.Entity("OperationsPortal.Api.Models.InventoryLocation", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("OperationsPortal.Api.Models.Item", b =>
                {
                    b.Navigation("BomHeaders");

                    b.Navigation("BomLines");

                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("OperationsPortal.Api.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("OperationsPortal.Api.Models.Site", b =>
                {
                    b.Navigation("Subsites");
                });

            modelBuilder.Entity("OperationsPortal.Api.Models.Subsite", b =>
                {
                    b.Navigation("InventoryLocations");
                });

            modelBuilder.Entity("OperationsPortal.Api.Models.UnitOfMeasure", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OperationsPortal.Api.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
